### ISSUE TITLE
Npm problem when installing

### ISSUE THREAD

**Issue by anbzerc** [Azeirah/scrybble-site#1]
Hi, 
First of all, thank you very much for your work on scrybble and for making it open source.
I have a problem when I try to install scrybble with the sail up -d command which seems to install the wrong version of npm. 
Here is the complete output of sail up -d [pastebin](https://pastebin.com/NM414U88) (the error message is at the bottom of pastebin). 

Thanks in advance and have a nice day!

**Comment by Azeirah** [comment]
I'm getting the same error when setting up. The version of the node/npm install script seems to be deprecated given the clear warning during build :p

```
================================================================================
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
================================================================================

                           SCRIPT DEPRECATION WARNING                    

  
  This script, located at https://deb.nodesource.com/setup_X, used to
  install Node.js is deprecated now and will eventually be made inactive.

  Please visit the NodeSource distributions Github and follow the
  instructions to migrate your repo.
  https://github.com/nodesource/distributions

  The NodeSource Node.js Linux distributions GitHub repository contains
  information about which versions of Node.js and which Linux distributions
  are supported and how to install it.
  https://github.com/nodesource/distributions


                          SCRIPT DEPRECATION WARNING

================================================================================
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
================================================================================

TO AVOID THIS WAIT MIGRATE THE SCRIPT
Continuing in 60 seconds (press Ctrl-C to abort) ...
```

I expect upstream sail doesn't have this issue, so I'll try updating sail first, see if that fixes the issue.

**Comment by Azeirah** [comment]
Yep, as expected this fixes the problem. I updated sail and npm now builds without an issue :)

I think the readme is not sufficient to set up the entire project, but I'll guide you through the entire process. The most obvious missing entry is the env file and build requirements for everything.

I'm considering moving remarks away from docker and installing it as a direct python dependency as well since that's the major blocker for local usage.

**Comment by Azeirah** [comment]
You will encounter more issues during installation, please open up another issue for what you run into, I'll fix things step-by-step.
