### ISSUE TITLE
Connect obsidian plugin to local server

### ISSUE THREAD

**Issue by anbzerc** [Azeirah/scrybble-site#10]
Ahhhh ! Is there a way to make the obsidian extension work with custom url ? I tried but I have Oauth authentification problem. When sending a post request to the local api with postman, the server returns
`{
    "error": "invalid_client",
    "error_description": "Client authentication failed",
    "message": "Client authentication failed"
}`

**Comment by Azeirah** [comment]
I think that's because Laravel Passport isn't initialised yet, it's what allows API usage from external applications.

https://laravel.com/docs/10.x/passport

I'll look into it as well, I believe it's just a matter of running some set-up command for passport, but it might be a little bit more than just that. Needs to be part of the set-up in the readme.

**Comment by Azeirah** [comment]
Note that after setting up the API, it's likely you'll run into CORS issues as well, although we'll deal with that next.

I'm only anticipating one last problem after that, and then it'll basically be ready to use. Better than I expected!

**Comment by Azeirah** [comment]
No CORS issues, set-up better than I expected whaha. The plugin itself needs some changes, I made those to my dev Obsidian plugin already.

You'll need to configure two things

1. The host url, so for a self-hosted variant that's most likely just `http://localhost`
2. The client secret, you can find this by visiting `http://localhost/client-secret`

![afbeelding](https://github.com/Azeirah/scrybble-site/assets/4040870/87a41d60-3be3-497a-857a-cdcbcddd60eb)

**Comment by Azeirah** [comment]
I'll need to push this updated plugin to the obsidian community plugins store, I hope I can get to that tomorrow.

**Comment by Azeirah** [comment]
> Ok thank you so much 😄

I pushed the update this afternoon, you should be able to update to the newest version 2.29.0 via obsidian's plugin manager
