### ISSUE TITLE
License

### ISSUE THREAD

**Issue by anbzerc** [Azeirah/scrybble-site#8]
I managed to install it. So now my question is, is it possible to run scrybble locally without a license (maybe you don't want to, I'd understand.) ?

**Comment by Azeirah** [comment]
Yes, it's definitely possible. It's a bit convoluted to do manually without instructions, but from the top of my head I believe it should work if you create a user with admin rights.

By default, the user with id of 1 is assumed to be an admin. Starting from an empty DB, your first user will have id 1.

I think it's possible that the UI will still not let you through if you're an admin though, I'll check it out this evening.

I'm almost 100% certain that if you add a new row to the `gumroad_licenses` table, with valid=true and anything in the license field, user_id = 1, the UI will let you through. Normally this row is only created after validating the license you put into the input field from the frontend, but if you create it manually it should be fine.

```
$license = new GumroadLicense();
$license->user_id = 1;
$license->license = "Doesn't matter because I'm a developer mwhahaha"
$license->valid = true;
$license->last_validated_at = now();
$license->save();
```

I think it makes more sense to just skip this check altogether for the admin user, but I'll take a look later.

**Comment by Azeirah** [comment]
:)
